### ISSUE TITLE
L1 Mastering Font checklist

### ISSUE THREAD

**Issue by vv-monsalve** [vv-monsalve/TypeSetIt-projects#1]
### L1 Mastering Font checklist

**Diacritics**
- [ ] Ensure the design of marks is consistent with the font and among themselves  (in terms of balance, weight, size, and contrast). See the [Diacritics requirements](https://googlefonts.github.io/gf-guide/diacritics.html) section of the GF-Guide
- [ ] Make sure the outilnes are in the combining marks.
- [ ] Add anchors as needed
- [ ] Ensure the diacritics consistency with the font characteristics + among related marks, [see issue of reference](https://github.com/googlefonts/italianno/issues/6).
- [ ] Adjust left and right sidebearings of all the comb marks to 0 (so that they are easy to edit)
- [ ] Adjust position using glyphs app locked guidelines.
- [ ] Decomposed transformed components, review proportions ensuring round coordinates + nodes at extremes
- [ ] Test the comb marks by inspecting each of them in context (open the mark, right-click, and choose `Show all glyphs that use this glyph as a component` option).
- [ ] Inspect and balance the below marks (size, weight, balance) e.g. `ogonek` `cedilla` to avoid huge marks
- [ ] Create [Catalan Punt Volat ](https://glyphsapp.com/learn/localize-your-font-catalan-punt-volat)
- [ ] Delete the legacy marks and add them back so they are made using the combining marks as components.
- [ ] Create combining `.case` marks by making them less tall and less narrow while keeping them at the same weight (preferably at the height they are intended to use, to be able to inspect them in their context)
- [ ] Create the Vietnamese diacritics by using a specific anchor (e.g. topviet) so those composite glyphs could be automatically updated
- [ ] Make composite glyphs for the entire font.
- [ ] Review and adjust the anchor's position.

**Glyphs & Outlines**
- [ ] Create the missing glyphs to cover the Latin Core and Plus GF encodings if they are easy-to-go cases. Otherwise, please report them to the designer in the Design Issue.
- [ ] Inspect all the included glyphs has the Upper and Lowercase. 
- [ ] Ensure the above item by inspecting there are no glyphs with double encodings (Uppers + lowercase)
- [ ] Decompose the Currency symbols to avoid inconsistencies when the current components are changed (e.g. hyphen)
- [ ] Ensure the currency symbols consistency (size, weight) with the font.  
- [ ] Create/fix kerning groups for the font
- [ ] Inspect current kerning and delete the pairs that are not needed or not ideal (e.g. some numerals and quotes)
- [ ] Check kerning and spacing by using the .txt files. Fixing any kerning and spacing critical cases (covering the most common kerning pairs).
- [ ] After the revision to numerals spacing/kerning generate again the `.lf` using the main version (e.g. zero=zero.lf) 
- [ ] Check the spacing of fina glyphs to avoid crashes or collisions. [Issue of reference](https://github.com/googlefonts/comforter/issues/7)
- [ ] Check `@` `¿?` `¡!` `””` `«»` and overall punctuation consistency, position, and spacing is ok. Use key sidebearings + kerning groups to ensure consistency. Include `//` kerning. [MsMadi reference](https://github.com/googlefonts/ms-madi/issues/2#issuecomment-1073170407)
- [ ] Ensure there is no punctuation with components at the same position (e.g. ellipsis)
- [ ] Run the automatic Glyphsapp command: `Resolve all metrics` to update the metrics in the entire font.
- [ ] Check everything once again by going glyph by glyph.
- [ ] Inspect the ligatures coherence with the font (shape, spacing/kerning)
- [ ] Inspect/solve `fraction` consistency with the fractions. Adjust its sidebearings (negative).

**OT Features**
- [ ] Check OpenType features and see if all listed are valid. E.g. if `.fina` glyphs are actually ending shapes or SSs are not repeated under different names.
- [ ] Create Lookup for positional alternates for `fina` and `init` cases. [Luxurious as reference case](https://github.com/googlefonts/luxurious/tree/master/sources)
- [ ] All the features/classes that could be done automatically to be done in that way, e.g. `All Letters` 
- [ ] Inspect if Stylistic Sets have the right suffix (ss01 instead of .001 etc) glyphs and generate the automatic OpenType code.
- [ ] Check if there any Stylistic Set should be treated as any other feature, e.g. `SmallCaps` or `osf`.
- [ ] Add names to each Stylistic Set
- [ ] Check if the OpenType code has any errors. Hit the `update` & `compile` buttons to check everything is working well.

**Testing changes**
- [ ] Inspect the font created by the CI GHA to check production errors. If the action isn't included yet in the repo, export and test the font using Glyphs.
- [ ] Check the before and after font
- [ ] Check the font on `gen-html proof` to see if it's working well on web. Use the `--imgs` flag to produce images.
- [ ] Commit and make PR using images.

**Comment by vv-monsalve** [comment]
- If the designer is not using the best marks that can be found in the source file, as happened in `RUSerius` case, the best cases should be taken to improve the diacritics.
- If the marks are not consistent with the font characteristics, have real issues e.g. in terms of size or weight, and there are not better cases within the font to work on, please file an Issue tagging me and Dave to evaluate the situation.
